export const ADD_TO_CART = "ADD_TO_CART"
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";

export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";

export const PRODUCT_REVIEW_SAVE_FAIL = "PRODUCT_REVIEW_SAVE_FAIL";
export const PRODUCT_REVIEW_SAVE_REQUEST = "PRODUCT_REVIEW_SAVE_REQUEST";
export const PRODUCT_REVIEW_SAVE_RESET = "PRODUCT_REVIEW_SAVE_RESET";
export const PRODUCT_REVIEW_SAVE_SUCCESS = "PRODUCT_REVIEW_SAVE_SUCCESS";

export const PRODUCTS_REQUEST_FAIL = "PRODUCTS_REQUEST_FAIL";
export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const PRODUCTS_REQUEST_SUCCESS = "PRODUCTS_REQUEST_SUCCESS";

export const PRODUCTS_SAVE_FAIL = "PRODUCTS_SAVE_FAIL";
export const PRODUCTS_SAVE_REQUEST = "PRODUCTS_SAVE_REQUEST";
export const PRODUCTS_SAVE_SUCCESS = "PRODUCTS_SAVE_SUCCESS";

export const REGISTER_FAIL = "REGISTER_FAIL"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_REQUEST = "REGISTER_REQUEST"


export const SIGN_IN_FAIL = "SIGN_IN_FAIL"
export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"